apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: <ACR_LOGIN_SERVER>/demo-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
